/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import database.Koneksi;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author USER
 */
public class LaporanPeminjamanKaset extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LaporanPeminjamanKaset.class.getName());
    Connection cn = Koneksi.getConnection();
    /**
     * Creates new form LaporanPeminjamanKaset
     */
    public LaporanPeminjamanKaset() {
        initComponents();
        showData();
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TFJudulKaset = new javax.swing.JTextField();
        TFDurasi = new javax.swing.JTextField();
        CBJenis = new javax.swing.JComboBox<>();
        BTambah = new javax.swing.JButton();
        BHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TKaset = new javax.swing.JTable();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama: Raka Restu Saputra");

        jLabel2.setText("NPM: 247006111172");

        jLabel3.setText("Kelas: F");

        jLabel4.setText("Laporan Peminjaman Kaset");

        jLabel5.setText("Judul Kaset");

        jLabel6.setText("Durasi (Hari)");

        jLabel7.setText("Jenis");

        CBJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VCD" }));

        BTambah.setText("Tambah");
        BTambah.addActionListener(this::BTambahActionPerformed);

        BHapus.setText("Hapus");
        BHapus.addActionListener(this::BHapusActionPerformed);

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        TKaset.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Judul Kaset", "Durasi", "Jenis"
            }
        ));
        TKaset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TKasetMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TKaset);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(BTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(60, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(65, 65, 65)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TFJudulKaset)
                                            .addComponent(TFDurasi)
                                            .addComponent(CBJenis, 0, 228, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TFJudulKaset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addComponent(TFDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CBJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTambah)
                    .addComponent(BHapus))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahActionPerformed
        String judul = TFJudulKaset.getText();
        String durasi = TFDurasi.getText();
        String jenis = (String) CBJenis.getSelectedItem();
        String sql = "INSERT INTO `kaset` (`judul_kaset`, `durasi`, `jenis`) VALUES ('" + judul + "',"
                + "'" + durasi + "', '" + jenis + "') ";
        try {
            Statement statement = cn.createStatement();
            statement.execute(sql);
            showData();
            JOptionPane.showMessageDialog(this, "Berhasil Menambahkan Data", "Berhasil", JOptionPane.DEFAULT_OPTION);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal Menambahkan Data", "Terjadi Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BTambahActionPerformed

    private void BHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapusActionPerformed
        int baris = TKaset.getSelectedRow();
        if (baris == -1) {
            JOptionPane.showMessageDialog(this, "Silakan pilih data yang mau dihapus pada tabel!", "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        String id = TKaset.getValueAt(baris, 1).toString();
        int konfirmasi = JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin menghapus data kaset: " + id + "?",
                "Konfirmasi Hapus",
                JOptionPane.YES_NO_OPTION);
        if (konfirmasi == JOptionPane.YES_OPTION) {
            try {
                Statement s = cn.createStatement();
                String sql = "DELETE FROM kaset WHERE judul_kaset = '" + id + "'";
                System.out.println("Query Eksekusi: " + sql);
                int dataTerhapus = s.executeUpdate(sql);
                if (dataTerhapus > 0) {
                    JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
                    showData();
                } else {
                    JOptionPane.showMessageDialog(this, "Data tidak ditemukan atau sudah terhapus.");
                }
                s.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Gagal Menghapus Data: " + e.getMessage(), "Error Database",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BHapusActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
//        int row = jTable2.getSelectedRow();
//        if (row >= 0) {
//            TFJudulKaset.setText(jTable2.getValueAt(row, 1).toString());
//            TFDurasi.setText(jTable2.getValueAt(row, 2).toString());
//            CBJenis.setSelectedItem(jTable2.getValueAt(row, 3).toString());
//        }
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void TKasetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TKasetMouseClicked
        int row = jTable2.getSelectedRow();
        if (row >= 0) {
    
            TFJudulKaset.setText(jTable2.getValueAt(row, 1).toString());
            TFDurasi.setText(jTable2.getValueAt(row, 2).toString());
            CBJenis.setSelectedItem(jTable2.getValueAt(row, 3).toString());
        }
    }//GEN-LAST:event_TKasetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LaporanPeminjamanKaset().setVisible(true));
    }
    
    public void showData() {
        try {
            Statement statement = cn.createStatement();
            ResultSet result = statement.executeQuery("SELECT * FROM `kaset`");
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Id");
            model.addColumn("Judul Kaset");
            model.addColumn("Durasi");
            model.addColumn("Jenis");
            while (result.next()) {
                Object[] data = {
                    result.getString("id"),
                    result.getString("judul_kaset"),
                    result.getString("durasi"),
                    result.getString("jenis")
                };
                model.addRow(data);

            }
            TKaset.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal Menampilkan Data: " + e.getMessage(), "Terjadi Kesalahan",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void bersihkanForm() {
        TFJudulKaset.setText("");
        TFDurasi.setText("");
        CBJenis.setSelectedIndex(0);
        TFJudulKaset.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BHapus;
    private javax.swing.JButton BTambah;
    private javax.swing.JComboBox<String> CBJenis;
    private javax.swing.JTextField TFDurasi;
    private javax.swing.JTextField TFJudulKaset;
    private javax.swing.JTable TKaset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
